name: Run Selenium Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposit√≥rio
        uses: actions/checkout@v3

      - name: Instalar Chromium, Chromedriver e Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium chromium-driver python3-pip
          
          python3 -m pip install --upgrade pip
          pip install selenium

      - name: Executar bot
        run: |
          python3 robor.py
